/**
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is automatically generated by the Chassis Astro Integration.
 * It contains the type definitions for the components that are auto imported in all pages.
 * @see packages/website/src/libs/astro.ts
 */
export declare global {
  export const AddedIn: typeof import('@ozgurgunes/chassis-docs/shortcodes/AddedIn.astro').default
  export const Callout: typeof import('@ozgurgunes/chassis-docs/shortcodes/Callout.astro').default
  export const Code: typeof import('@ozgurgunes/chassis-docs/shortcodes/Code.astro').default
  export const CxTable: typeof import('@ozgurgunes/chassis-docs/shortcodes/CxTable.astro').default
  export const Example: typeof import('@ozgurgunes/chassis-docs/shortcodes/Example.astro').default
  export const Placeholder: typeof import('@ozgurgunes/chassis-docs/shortcodes/Placeholder.astro').default
  export const Blockquote: typeof import('@shortcodes/Blockquote.astro').default
}
