title:                  "Chassis UI"
baseURL:                "https://chassis-ui.com"

docsDir:                "."
docsPath:                "/docs"

subtitle:               "Design System for Scale & Sync"
description:            "Open-source design system with design tokens, semantic CSS, and Figma integration. Build consistent, accessible web experiences faster."
authors:                "Ozgur Gunes and Chassis UI contributors"

current_version:        "0.1.0"
docs_version:           "0.1"
github_org:             "https://github.com/chassis-ui"
repo:                   "https://github.com/chassis-ui/docs"
x:                      "chassis_ui"

analytics:
  google_id:            "G-QGR8C28VYN"

algolia:
  app_id:               "MEJ97SH293"
  api_key:              "df6a517a37c3973122cfc40042055f9c"
  index_name:           "chassis-docs"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  6

blog:
  pageSize:             2
