title:                  "Chassis - Docs"
baseURL:                "https://chassis-ui.com"

docsDir:                "."
docsPath:                "/docs"

subtitle:               "Documentation for the Chassis design system."
description:            "Comprehensive documentation for Chassis CSS framework, design tokens, and Figma components."
authors:                "Ozgur Gunes and Bootstrap contributors"

current_version:        "0.1.0"
docs_version:           "0.1"
github_org:             "https://github.com/ozgurgunes"
repo:                   "https://github.com/chassis-ui/docs"
x:                      "chassisui"

analytics:
  google_id:            "G-QGR8C28VYN"

algolia:
  app_id:               "MEJ97SH293"
  api_key:              "df6a517a37c3973122cfc40042055f9c"
  index_name:           "chassis-docs"

anchors:
  min:                  2
  max:                  4

toc:
  min:                  2
  max:                  4

blog:
  pageSize:             2
