import fs from 'node:fs'
import path from 'node:path'
import type { AstroIntegration } from 'astro'

interface MdxjsEsmNode {
  type: 'mdxjsEsm'
  value: string
  data: { estree: object }
}

function buildImportsNode(imports: string[]): MdxjsEsmNode {
  const body = imports.map((filePath) => {
    const name = path.parse(filePath).name.replaceAll(/[^\w\d]/g, '')
    return {
      type: 'ImportDeclaration',
      specifiers: [{ type: 'ImportDefaultSpecifier', local: { type: 'Identifier', name } }],
      source: { type: 'Literal', value: filePath, raw: JSON.stringify(filePath) }
    }
  })

  return {
    type: 'mdxjsEsm',
    value: '',
    data: { estree: { type: 'Program', sourceType: 'module', body } }
  }
}

export interface ChassisAutoImportOptions {
  /** Absolute path to the docs site root (e.g. `getDocsFsPath()`). Used for the
   *  site-local shortcodes directory and the type definitions output path. */
  docsPath: string
  /** Absolute path to the directory containing `node_modules`. Defaults to
   *  `docsPath` when omitted — override when `node_modules` lives at the repo root. */
  modulesPath?: string
}

function scanComponents({ docsPath, modulesPath = docsPath }: ChassisAutoImportOptions) {
  const dirs = [
    path.join(modulesPath, 'node_modules/@chassis-ui/docs/src/components/shortcodes'),
    path.join(docsPath, 'src/components/shortcodes')
  ]

  const components: string[] = []
  const definitions: string[] = []

  for (const dir of dirs) {
    if (!fs.existsSync(dir)) continue
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile()) continue
      components.push(`${dir}/${entry.name}`)
      if (entry.name.endsWith('.astro')) {
        const importPath = dir.includes('@chassis-ui/docs')
          ? `@chassis-ui/docs/shortcodes`
          : `@shortcodes`
        definitions.push(
          `export const ${entry.name.replace('.astro', '')}: typeof import('${importPath}/${entry.name}').default`
        )
      }
    }
  }

  return { components, definitions }
}

/**
 * Astro integration that writes the auto-import type definitions file, and a
 * remark plugin factory for injecting shortcode imports into every MDX file.
 *
 * Replaces `astro-auto-import`, which triggers a deprecation warning in Astro 7.
 *
 * @example
 * ```ts
 * // astro.ts
 * const { integration, plugin } = chassisAutoImport({ docsPath: getDocsFsPath(), modulesPath: process.cwd() })
 *
 * // astro.config.ts
 * markdown: getDocsMarkdownConfig({ remarkPlugins: [plugin()] })
 * integrations: [integration()]
 * ```
 */
export function chassisAutoImport(options: ChassisAutoImportOptions): {
  /** Astro integration that writes `src/types/auto-import.d.ts`. */
  integration: () => AstroIntegration
  /** Factory for the remark plugin that injects imports into every `.mdx` file. */
  plugin: () => ReturnType<typeof createAutoImportPlugin>
} {
  const { components, definitions } = scanComponents(options)
  const typeDefinitionsPath = path.join(options.docsPath, 'src/types/auto-import.d.ts')

  return {
    integration: () => ({
      name: 'chassis-auto-import',
      hooks: {
        'astro:config:setup': () => {
          fs.writeFileSync(
            typeDefinitionsPath,
            `/**
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is automatically generated by the Chassis Astro Integration.
 * It contains the type definitions for the components that are auto imported in all pages.
 */
export declare global {
  ${definitions.join('\n  ')}
}
`
          )
        }
      }
    }),
    plugin: () => createAutoImportPlugin(components)
  }
}

/**
 * Returns a remark plugin that prepends import statements for the given component
 * paths into every `.mdx` file.
 */
export function createAutoImportPlugin(imports: string[]) {
  const importsNode = buildImportsNode(imports)

  return function remarkAutoImport() {
    return function (tree: any, vfile: any) {
      if (!vfile.basename?.endsWith('.md')) {
        tree.children.unshift(importsNode)
      }
    }
  }
}
