import fs from 'node:fs'
import path from 'node:path'
import { resolvePackageFilePath } from './paths'

interface MdxjsEsmNode {
  type: 'mdxjsEsm'
  value: string
  data: { estree: object }
}

function getComponentName(filePath: string): string {
  return path.parse(filePath).name.replaceAll(/[^\w\d]/g, '')
}

function buildImportsNode(imports: string[]): MdxjsEsmNode {
  const body = imports.map((filePath) => {
    const name = getComponentName(filePath)
    return {
      type: 'ImportDeclaration',
      specifiers: [{ type: 'ImportDefaultSpecifier', local: { type: 'Identifier', name } }],
      source: { type: 'Literal', value: filePath, raw: JSON.stringify(filePath) }
    }
  })

  return {
    type: 'mdxjsEsm',
    value: '',
    data: { estree: { type: 'Program', sourceType: 'module', body } }
  }
}

export interface ChassisAutoImportOptions {
  /**
   * The site's root.
   * @default process.cwd()
   */
  root?: string
  /**
   * The site's own shortcodes, relative to `root`. A component here replaces the component
   * of the package that has the same name.
   * @default 'src/components/shortcodes'
   */
  dir?: string
  /** Names of the only shortcodes of the package to import, e.g. `['Code', 'Callout']`. */
  include?: string[]
  /** Names of shortcodes of the package to leave out, e.g. `['Icon']`. */
  exclude?: string[]
  /**
   * Absolute path of the package's shortcodes. Found from the package's own location when
   * omitted.
   */
  packageDir?: string
}

export interface ChassisAutoImport {
  /** Import specifiers of the components, in import order. */
  imports: string[]
  /** Source of a declaration file that makes the components global in MDX files. */
  typeDefinitions: string
  /** Factory for the remark plugin that injects the imports into every `.mdx` file. */
  plugin: () => ReturnType<typeof createAutoImportPlugin>
}

function listFiles(directory: string): string[] {
  if (!fs.existsSync(directory)) return []

  return fs
    .readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isFile() && !entry.name.startsWith('.'))
    .map((entry) => entry.name)
    .sort()
}

/**
 * Finds the shortcodes of the package and of the site, and returns what is needed to import
 * them into every MDX file. The `chassisDocs()` integration calls it. A site calls it only
 * to build its own markdown configuration.
 */
export function chassisAutoImport(options: ChassisAutoImportOptions = {}): ChassisAutoImport {
  const {
    root = process.cwd(),
    dir = 'src/components/shortcodes',
    include,
    exclude = [],
    packageDir = resolvePackageFilePath('shortcodes')
  } = options

  const siteDir = path.resolve(root, dir)
  const siteFiles = listFiles(siteDir)
  const siteNames = new Set(siteFiles.map(getComponentName))

  const packageFiles = listFiles(packageDir).filter((file) => {
    const name = getComponentName(file)

    if (siteNames.has(name) || exclude.includes(name)) return false

    return include ? include.includes(name) : true
  })

  // The package's components are imported by specifier, not by path. The path of an
  // installed package is outside the site, where the dev server refuses to serve files.
  const components = [
    ...packageFiles.map((file) => ({ file, source: `@chassis-ui/docs/shortcodes/${file}` })),
    ...siteFiles.map((file) => ({ file, source: path.join(siteDir, file) }))
  ]

  const definitions = components
    .filter(({ file }) => file.endsWith('.astro'))
    .map(
      ({ file, source }) =>
        `export const ${getComponentName(file)}: typeof import('${source}').default`
    )

  const imports = components.map(({ source }) => source)

  return {
    imports,
    typeDefinitions: `/**
 * Generated by the integration of @chassis-ui/docs.
 * The components that are imported into every MDX file.
 */
export declare global {
  ${definitions.join('\n  ')}
}
`,
    plugin: () => createAutoImportPlugin(imports)
  }
}

/**
 * Returns a remark plugin that prepends import statements for the given component
 * paths into every `.mdx` file.
 */
export function createAutoImportPlugin(imports: string[]) {
  const importsNode = buildImportsNode(imports)

  return function remarkAutoImport() {
    return function (tree: any, vfile: any) {
      if (!vfile.basename?.endsWith('.md')) {
        tree.children.unshift(importsNode)
      }
    }
  }
}
