import fs from 'node:fs'
import path from 'node:path'
import astroAutoImport from 'astro-auto-import'
import { getDocsFsPath } from './path'

// A list of directories in `src/components` that contains components that will be auto imported in all pages for
// convenience.
// Note: adding a new component to one of the existing directories requires a restart of the dev server.
const autoImportedComponentDirectories = [
  path.join(getDocsFsPath(), 'node_modules/@ozgurgunes/chassis-docs/src/components/shortcodes'),
  path.join(getDocsFsPath(), 'src/components/shortcodes')
]

// Generate the type definitions for all the auto imported components and write them to a file that will be included in
// the main `tsconfig.json` file to make the types available globally in the project.
// Note: this function is called each time the integration is loaded, so during dev server start and during a build.
export default function () {
  const autoImportedComponents: string[] = []
  const autoImportedComponentDefinitions: string[] = []

  for (const autoImportedComponentDirectory of autoImportedComponentDirectories) {
    const components = fs.readdirSync(autoImportedComponentDirectory, {
      withFileTypes: true
    })

    for (const component of components) {
      if (component.isFile()) {
        autoImportedComponents.push(`${autoImportedComponentDirectory}/${component.name}`)

        if (component.name.endsWith('.astro')) {
          const importPath = autoImportedComponentDirectory.includes('@ozgurgunes/chassis-docs')
            ? `@ozgurgunes/chassis-docs/shortcodes`
            : `@shortcodes`
          autoImportedComponentDefinitions.push(
            `export const ${component.name.replace('.astro', '')}: typeof import('${importPath}/${component.name}').default`
          )
        }
      }
    }
  }

  const autoImportedComponentDefinition = `/**
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is automatically generated by the Chassis Astro Integration.
 * It contains the type definitions for the components that are auto imported in all pages.
 * @see packages/website/src/libs/astro.ts
 */
export declare global {
  ${autoImportedComponentDefinitions.join('\n  ')}
}
`

  fs.writeFileSync('./src/types/auto-import.d.ts', autoImportedComponentDefinition)

  return astroAutoImport({
    imports: autoImportedComponents
  })
}
